# channels:
#   - conda-forge
# dependencies:
#   - python=3.11.0
#   - pip<=25.0.1
#   - pip:
#       - mlflow==3.1.0
#       - cloudpickle==3.1.1
#       - numpy==2.1.3
#       - pandas==2.2.3
#       - scikit-learn==1.6.1
#       - scipy==1.15.3
# name: mlflow-env
name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - scikit-learn=1.6.1
  - numpy
  - scipy
  - pip
  - pip:
      - mlflow==2.19.0
      - gunicorn
      - matplotlib
      - seaborn
      - cloudpickle
